name: Build and Test

on:
  push:
jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: dotnet build --configuration Release
      - name: Retrieve .runsettings file
        run: |
          $env:RUNSETTINGS_FILE | Out-File -FilePath .runsettings -Encoding utf8
        shell: pwsh
        env:
          RUNSETTINGS_FILE: ${{ secrets.RUNSETTINGS_FILE }}
      - name: Test
        run: dotnet test --configuration Release --no-build --settings .runsettings
